### ISSUE TITLE
"self" relation keyword is reserved in Dedalus/Datalog

### ISSUE THREAD

**Issue by davidchuyaya** [hydro-project/dfir-datalog#5]
This is the error I get whenever any relations in Dedalus are named `self`. Renaming the relation solves the problem.
Would be nice to have a list of reserved names; or, if we're not allowed to use any rust keywords or hydroflow variable names, to throw the appropriate error.

```
running 1 test
thread 'tests::test_vote' panicked at 'expected identifier', /Users/davidchu/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.105/src/parse_quote.rs:120:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/panicking.rs:147:5
   3: syn::parse_quote::parse
             at /Users/davidchu/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.105/src/parse_quote.rs:120:21
   4: hydroflow_datalog_core::gen_hydroflow_graph
             at ./src/lib.rs:53:46
   5: hydroflow_datalog_core::tests::test_vote
             at ./src/lib.rs:596:9
   6: hydroflow_datalog_core::tests::test_vote::{{closure}}
             at ./src/lib.rs:595:20
   7: core::ops::function::FnOnce::call_once
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/dc1d9d50fba2f6a1ccab8748a0050cde38253f60/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test tests::test_vote ... FAILED
```

**Comment by davidchuyaya** [comment]
`in` is also a keyword.
